name: magdsoft_flutter_structure
description: magdsoft mobile application structure for flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.17
  easy_localization: ^3.0.1
  fluttertoast: ^8.1.2
  sizer: ^2.0.15
  flutter_svg_provider: ^1.0.3
  flutter_staggered_grid_view: ^0.6.2
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/i18n/
    - assets/Inter_Font/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter_Font/Inter-Thin.ttf
        - asset: assets/Inter_Font/Inter-ExtraLight.ttf
        - asset: assets/Inter_Font/Inter-Light.ttf
        - asset: assets/Inter_Font/Inter-Regular.ttf
        - asset: assets/Inter_Font/Inter-Medium.ttf
        - asset: assets/Inter_Font/Inter-SemiBold.ttf
        - asset: assets/Inter_Font/Inter-Bold.ttf
        - asset: assets/Inter_Font/Inter-ExtraBold.ttf
        - asset: assets/Inter_Font/Inter-Black.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
